# Generated by Django 3.2.4 on 2021-06-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('GmailId', models.EmailField(max_length=254)),
                ('File', models.ImageField(upload_to='')),
                ('Likes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='guser',
            name='id',
        ),
        migrations.AlterField(
            model_name='guser',
            name='GmailId',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
