# Generated by Django 3.2.4 on 2021-06-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_lost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lost',
        ),
    ]
