# Generated by Django 3.2.4 on 2021-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210623_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
